### ISSUE TITLE
Disallow __setattr__?

### ISSUE THREAD

**Issue by spacether** [corenting/immutabledict#229]
Thank you for your work on this library. I prefer it to frozendict because you implemented generics, which I need.

calling `setattr(immutabledict_instance, 'someProp', 'some val')` works.
Should it?
If it should not, how about adding the `__setattr__` method and have it raise an exception?

**Comment by corenting** [comment]
Thanks for the message! 

Indeed the immutability is not fully strict. I tried to keep the implementation close to [the original frozendict implementation](https://github.com/slezica/python-frozendict) and did not change the `__setattr__` method or other methods, especially since in the case of the `__setattr__` method it still needs to work during initialization.

Other projects like [the new frozendict](https://github.com/slezica/python-frozendict) or [gelidum](https://github.com/diegojromerolopez/gelidum) already implements more protections for immutability but it comes with more complexity, so I'm not sure if I will implement it for immutabledict.
